### ISSUE TITLE
没有LiveDataBus

### ISSUE THREAD

**Issue by KnightAndroid** [tanranran/HarmonyUtilCode#3]
如题

**Comment by ByteRax** [comment]
太忙了，库里有很多代码，没时间去整理写文档。就没提交源码，但是远程har 是有的

https://ohpm.openharmony.cn/#/cn/detail/@android_x%2Futilcode

**Comment by KnightAndroid** [comment]
希望能抽时间完善一下

**Comment by ByteRax** [comment]
> 希望能抽时间完善一下

提交了

https://github.com/tanranran/HarmonyUtilCode/blob/master/utilcode/src/main/ets/LiveDataBus.ets
