### ISSUE TITLE
LiveDataBus 广播注销不生效

### ISSUE THREAD

**Issue by KnightAndroid** [tanranran/HarmonyUtilCode#4]
LiveDataBus.removeObserve 注销监听这个方法我调用了，然后再次调用广播post 上次广播会同时调用，麻烦看看怎么回事？

**Comment by KnightAndroid** [comment]
经排查：
emitter.off(eventName, realCallback) 这行有问题 我断点realCallback 未定义
改成 emitter.off(eventName) 就成功

**Comment by ByteRax** [comment]
> 经排查： emitter.off(eventName, realCallback) 这行有问题 我断点realCallback 未定义 改成 emitter.off(eventName) 就成功

麻烦贴一下有问题的代码，我排查一下。

emitter.off(eventName)  会注销所有叫eventName 的监听，某些场景是很多个页面需要注册同一个eventName，如果直接这样注销，会导致其它位置注册的全部失效。

**Comment by KnightAndroid** [comment]
removeObserve(eventName: string, callback: () => void) {
    let realCallback: Callback<emitter.EventData>
    if (this.callbackMap.hasKey(eventName)) {
      realCallback = this.callbackMap.get(eventName).get(callback)
    }
    if (!this.callbackMap.hasKey(eventName) || this.callbackMap.get(eventName).length == 0) {
      emitter.off(eventName)
    } else {
      emitter.off(eventName, realCallback)   //此行 realCallback 有问题  也不知道是不是我调用方法有问题？?
      this.callbackMap.get(eventName).remove(callback)
    }
  }

**Comment by tanranran** [comment]
> removeObserve

再麻烦贴一下调用的代码吧，我复现一下测一下

**Comment by KnightAndroid** [comment]
EventBus.removeObserve("test")

**Comment by KnightAndroid** [comment]
EventBus.observe<number>("test", (data: number) => {
      this.currentProgress = data
    }, this.lifecycle)

**Comment by ByteRax** [comment]
> EventBus.observe("test", (data: number) => { this.currentProgress = data }, this.lifecycle)

已修复【之前在其它项目已修复，忘记同步到这个库里面了】，您替换一下LiveDataBus 的代码

https://github.com/tanranran/HarmonyUtilCode/blob/master/utilcode/src/main/ets/LiveDataBus.ets

**Comment by KnightAndroid** [comment]
好的 非常感谢

**Comment by KnightAndroid** [comment]
还有一个问题 ，为啥 第一次发了一次，广播 ，第二次再发广播，会有两条？

**Comment by ByteRax** [comment]
> 还有一个问题 ，为啥 第一次发了一次，广播 ，第二次再发广播，会有两条？

检查下是否注册了两遍，或者页面注册后，页面退出后，未取消注册

**Comment by KnightAndroid** [comment]
你好 有一个问题，我在一个组件监听了方法，能不能主动在其他地方取消监听 例如：EventBus.removeObserve("test",方法) 我在其他地方引用不了这个地方，导致取消监听不了，能否有其他方法？

**Comment by ByteRax** [comment]
> 你好 有一个问题，我在一个组件监听了方法，能不能主动在其他地方取消监听 例如：EventBus.removeObserve("test",方法) 我在其他地方引用不了这个地方，导致取消监听不了，能否有其他方法？

可以自定义一个controller 类
```typescript
@Component
@Preview
export struct LiveDataBusFragment {
  componentAController:ComponentAController=new ComponentAController()
  build() {
    Stack() {
      ComponentA({
        componentAController:this.componentAController
      })
      Button('取消组件A中的监听').onClick(()=>{
        this.componentAController.removeObserveCallback?.()
      })
    }
  }
}
class ComponentAController{
  removeObserveCallback?: () => void
}
@Component
@Preview
export struct ComponentA {
  componentAController?:ComponentAController
  aboutToAppear(): void {
    if(this.componentAController){
      this.componentAController.removeObserveCallback = () => {
        EventBus.removeObserve("test",方法)
      }
    }
  }

  build() {
  }
}
```
